[app]
# Version
version = "1.0.0"

# Enviroment (development|staging|production)
enviroment = "production"

[server]
# Port
port = 4175

# Address
address = "0.0.0.0"

# Auth keys
auth_keys = ["authKey1", "authKey2", "authKey3"]

# Rate limiter
[server.rate_limiter]
max_requests = 20
expiration = "30s"

[logger]
# Level
level = "info"

[offstyledb]
# Max file size
max_file_size = 104857600 # 100 MB

# Receiver
receiver = "https://offstyles.tommyy.dev/api"
